### ISSUE TITLE
EPIC: Electron RDP *************

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#11541]
- [ ] https://github.com/rstudio/rstudio-pro/issues/2309
- [ ] https://github.com/rstudio/rstudio-pro/issues/3230
- [ ] https://github.com/rstudio/rstudio-pro/issues/3599

**Comment by mikebessuille** [comment]
Closing as the other issues in this list are now Epics.
