### ISSUE TITLE
Issue with Tracking Slides in Quarto Revealjs when using Callouts

### ISSUE THREAD

**Issue by jmgirard** [rstudio/rstudio#11614]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.0+548
    OS Version : Windows 11
    R Version : 4.2.1 

> RStudio 2022.07.0+548 "Spotted Wakerobin" Release (34ea3031089fa4e38738a9256d6fa6d70629c822, 2022-07-06) for Windows
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem

1. Create a new Quarto Presentation
2. Copy in the following code
3. Render the presentation
4. Navigate to Slide 4 or 5 in the Presentation pane
5. Click the "Edit" button in the Presentation pane

```
---
title: "Untitled"
format: revealjs
---

## Slide 1

Slide Text

## Slide 2

Slide Text

## Slide 3

::: {.callout-note icon="false"}
## Callout Caption

Callout Text
:::

## Slide 4

Slide Text

## Slide 5

Slide Text

```

### Describe the problem in detail

In a revealjs Quarto presentation, if you include a callout with a caption on one of your slides, it will break the ability to use the "Edit" button on all subsequent slides. Similarly, on subsequent slides, clicking "Render" will display the wrong slide in the presentation pane (which is really annoying and time-consuming to keep moving backwards).

I assume this is because the callout caption is also a heading element. However, changing the caption from H2 to H3, H4, etc. does not fix the problem. Perhaps RStudio could ignore headings within callouts or the callout captions could be configured in some other way that does not involve headings.

### Describe the behavior you expected

The cursor in the Source pane should move to line 23 (i.e., ## Slide 4). However, it moves to line 18 (i.e., ## Callout Caption).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jmgirard Thank you for raising the issue! We'll review it as we continue development of RStudio and its integration with Quarto.

**Comment by paulalexander66** [comment]
HOW THE F CAN I CREATE THE NEXT SLIDE

pls help
