### ISSUE TITLE
section collapse fails if braces between quotation marks

### ISSUE THREAD

**Issue by FelicienLL** [rstudio/rstudio#12293]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2
    OS Version      : Microsoft Windows 10
    R Version       : 4.2.0

### Steps to reproduce the problem
```r
# part 1 ----
"
if(brace){
section wrap fails
}
"

# part 2 ----
"Hello world"
```
### Describe the problem in detail
Dear RStudio team, 
See the screenshot below, the section collapse fails if a line only has one closing brace within a string.

Bugs with:
``` r
"
}
"
```
Is ok with : 
``` r
"
} 
"
```
Best regards

![image](https://user-images.githubusercontent.com/68648517/200018674-10fe1c2a-9f29-44a7-8b04-1291b52e914c.png)
### Describe the behavior you expected
![image](https://user-images.githubusercontent.com/68648517/200018615-638f58aa-3874-4a2c-abaa-8a945f7f4b19.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For reference, this is where the fold-related computations live:

https://github.com/rstudio/rstudio/blob/eb1f68475a8e53bfa5a351a4fcde08a8883c6b67/src/gwt/acesupport/acemode/r_code_model.js#L1289-L1495

I suspect there's a place where we're looking for open / close braces, but failing to check whether we're within a multiline string.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/blob/eb1f68475a8e53bfa5a351a4fcde08a8883c6b67/src/gwt/acesupport/acemode/r_code_model.js#L1465 feels suspicious.

**Comment by sharon-wang** [comment]
Confirming this can still be reproduced in `2023.03.0 Build 386 Cherry Blossom` on MacOS 12.6.

https://user-images.githubusercontent.com/25834218/229824260-f3d73191-35e6-40a8-84b3-d44241087331.mov

This also occurs in Qmd/Rmd files in R codeblocks:

````
```{r}
# part 1 ----
"
if(brace){
section wrap fails
}
"

# part 2 ----
"Hello world"
```
````
