### ISSUE TITLE
Epic: Key Binding bugs 2023

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#12798]
- [ ] https://github.com/rstudio/rstudio/issues/8864
- [ ] https://github.com/rstudio/rstudio/issues/11858
- [ ] https://github.com/rstudio/rstudio/issues/12388
- [ ] https://github.com/rstudio/rstudio/issues/12125
- [ ] https://github.com/rstudio/rstudio/issues/11753

When you start this epic, review any additional label:"key bindings" issues which may have been added to Backlog-1 after this epic was created.

**Comment by mikmart** [comment]
Should https://github.com/rstudio/rstudio/issues/12457 also be included?

**Comment by gtritchie** [comment]
Reviewed linked issues, closing Epic.
