### ISSUE TITLE
Epic: Visual Markdown bug fixes 2023

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#12794]
```[tasklist]
- [ ] https://github.com/rstudio/rstudio/issues/12257
- [ ] https://github.com/rstudio/rstudio/issues/12587
- [ ] https://github.com/rstudio/rstudio/issues/12227
- [ ] https://github.com/rstudio/rstudio-pro/issues/2350
- [ ] https://github.com/rstudio/rstudio/issues/11924
- [ ] https://github.com/rstudio/rstudio/issues/11858
- [ ] https://github.com/rstudio/rstudio/issues/12221
- [ ] https://github.com/rstudio/rstudio/issues/12353
- [ ] https://github.com/rstudio/rstudio/issues/12539
```

And: Search for other "visual markdown" issues in "Backlog-1" when this epic is started, which may not have been added to the above list when the epic was created.

**Comment by netique** [comment]
Maybe include also https://github.com/rstudio/rstudio/issues/12952.
