### ISSUE TITLE
Epic: Source Editor regressions 2023

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#12797]
- [ ] https://github.com/rstudio/rstudio/issues/11313 (also in Notebook Mode epic)
- [ ] https://github.com/rstudio/rstudio/issues/12348
- [x] https://github.com/rstudio/rstudio/issues/12504

### Multiline/Multicolumn/Block Selection (alt+select, alt+drag)
- [ ] https://github.com/rstudio/rstudio/issues/12470
- [ ] https://github.com/rstudio/rstudio/issues/12310
- [x] https://github.com/rstudio/rstudio/issues/12906
- [x] https://github.com/rstudio/rstudio/issues/12509

**Comment by gtritchie** [comment]
Reviewed linked issues, closing epic.
