### ISSUE TITLE
Epic: Notebook mode

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#12792]
- [x] https://github.com/rstudio/rstudio/issues/11995
- [ ] https://github.com/rstudio/rstudio/issues/6769
- [ ] https://github.com/rstudio/rstudio/issues/2501
- [x] https://github.com/rstudio/rstudio/issues/11313
- [ ] https://github.com/rstudio/rstudio/issues/11411
- [ ] https://github.com/rstudio/rstudio/issues/10677

**Comment by olivroy** [comment]
Maybe #13080 too!

**Comment by gtritchie** [comment]
Reviewed linked issues, closing epic.
