### ISSUE TITLE
Epic: Push-button deploy

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13040]
Now that Hadley has revised the internals/fixed a number of issues in `rsconnect` package, we can make some small changes to the Push-button deploy experience.

The first two are bad bugs that affect a failed publish
- [ ] https://github.com/rstudio/rstudio/issues/12707
- [ ] https://github.com/rstudio/rstudio/issues/12708 

This is a new feature that builds off the ability of `rsconnect::deployApp()` to send secure env variables so apps don't fail on publish (where failure would _also_ get better from above work).
- [ ] https://github.com/rstudio/rstudio/issues/13032

**Comment by jthomasmock** [comment]
@petetronic - this Epic (or some subset) would be a good set to prioritize
