### ISSUE TITLE
Not downloaded Github Copilot agent

### ISSUE THREAD

**Issue by arodionoff** [rstudio/rstudio#13630]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2023.12.0-daily+17 "Ocean Storm" Daily (53d38d369835fbbb48d0c5788e20121434d94749, 2023-09-13) for windows
    OS Version      : Windows 10 Pro
    R Version       : R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Tried to install on Windows the latest versions of RStudio Desktop 2023.09.0+433 **Desert Sunflower** and the latest version 2023.12-daily+17 **Ocean Storm** (both versions installed with administrator rights) to test **Github Copilot**, which was not yet installed on the computer for any kind of **IDE** .

However, in RStudio Desktop, the command `Tools -> Global Options -> Copilot -> Enable Github Copilot` caused an error. Since the file `https://rstudio.org/links/github-copilot/1358e8e45ecedc53daf971924a0541ddf6224faf` is NOT downloaded COMPLETELY, and therefore is not unzipped in the Copilot directory and the `agent.js` file in the dist subdirectory is not executed. You probably need to check the completeness of the file download based on the size of the resulting archive.

This failure befell me on various computers with Windows 10 Pro & Windows 11 Pro operating systems.
```[tasklist]
### Tasks
```

**Comment by ronblum** [comment]
@arodionoff Thank you for raising this issue! Once the installation fails this way, are you no longer given an option to install? If so, while we look into this, the following workaround might work: <kbd>Tools -> Show Command Palette -> Copilot Install Agent<kbd> which will give you the installation dialog pop-up.

**Comment by WiseGIS** [comment]
I am getting the same error message on the install.  The workaround did not work.

**Comment by arodionoff** [comment]
> @arodionoffСпасибо, что подняли этот вопрос! Если установка не удалась таким образом, у вас больше не будет возможности установить? Если да, то пока мы разбираемся в этом, может сработать следующий обходной путь:Tools -> Show Command Palette -> Copilot Install Agent which will give you the installation dialog pop-up.

I'll try, but can you tell me in which folder in Windows 11 Copilot will be placed?

**Comment by kevinushey** [comment]
I believe this issue should be resolved in the latest daily builds of RStudio, available at https://dailies.rstudio.com. Can you test and confirm?

**Comment by ronblum** [comment]
@arodionoff @WiseGIS Were you able to try out a more recent build of RStudio and did it work?

**Comment by WiseGIS** [comment]
Yes it did.  What I found was the Cisco agent / service my work installed
was blocking the connection to the AI service.  Once I turn that off it
works great.  I assumed it was rstudio after vscode worked but rstudio did
not work initially.

**Comment by jonvanausdeln** [comment]
@WiseGIS , thank you for confirming!
