### ISSUE TITLE
EPIC: Repos and package installation

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13779]
```[tasklist]
### Issues
- [ ] https://github.com/rstudio/rstudio/issues/10016
- [ ] https://github.com/rstudio/rstudio/issues/13650
- [ ] https://github.com/rstudio/rstudio/issues/13538
- [ ] https://github.com/rstudio/rstudio/issues/12648
- [ ] https://github.com/rstudio/rstudio/issues/13247
- [ ] https://github.com/rstudio/rstudio/issues/13141
- [ ] https://github.com/rstudio/rstudio/issues/12529
- [ ] https://github.com/rstudio/rstudio/issues/9959
- [ ] https://github.com/rstudio/rstudio/issues/8997
- [ ] https://github.com/rstudio/rstudio/issues/8722
- [ ] https://github.com/rstudio/rstudio/issues/11965
```
