### ISSUE TITLE
User Guide Cleanup

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#14555]
- [ ] **Formatting clean-up (https://github.com/rstudio/rstudio/issues/16003):** 

- [ ] **Images clean-up (https://github.com/rstudio/rstudio/issues/16012):**

- [ ] **Sweeping Copy Edit (https://github.com/rstudio/rstudio/issues/16014):**

**Plan for PRs**: coming soon

```[tasklist]
### Tasks
```

**Comment by AshleyHenry15** [comment]
@annikakrilov - feel free to chip away at this one. These "sub tasks" can be broken out into smaller issues.
