### ISSUE TITLE
Theme: Visual Editor

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#14639]
```[tasklist]
### Tasks
- [ ] #14508 
- [ ] #13388 
- [ ] #14331 
- [ ] #14409 
- [ ] #14376 
- [ ] #14314 
- [ ] #12496 
- [ ] #12353 
- [ ] #13427 
- [ ] #10823
- [ ] https://github.com/rstudio/rstudio/issues/11063
- [ ] https://github.com/rstudio/rstudio/issues/12663
- [ ] https://github.com/rstudio/rstudio/issues/12959
- [ ] https://github.com/rstudio/rstudio/issues/13605
- [ ] https://github.com/rstudio/rstudio/issues/14596
- [ ] https://github.com/rstudio/rstudio/issues/13634
- [ ] https://github.com/rstudio/rstudio/issues/9079
- [ ] https://github.com/rstudio/rstudio/issues/12587
- [ ] #11858 
- [ ] #12221 
- [ ] #12539 
- [ ] https://github.com/rstudio/rstudio/issues/14594
- [ ] https://github.com/rstudio/rstudio/issues/12462
- [ ] https://github.com/rstudio/rstudio/issues/12327
- [ ] https://github.com/rstudio/rstudio/issues/14549
- [ ] https://github.com/rstudio/rstudio/issues/13733
- [ ] https://github.com/rstudio/rstudio/issues/13696
- [ ] https://github.com/rstudio/rstudio/issues/13229
- [ ] https://github.com/rstudio/rstudio/issues/14219
- [ ] https://github.com/rstudio/rstudio/issues/14040
- [ ] https://github.com/rstudio/rstudio/issues/13096
- [ ] https://github.com/rstudio/rstudio/issues/13194
```
