### ISSUE TITLE
Tracking: Chromium 551420 (Emoji Rendering in Retina)

### ISSUE THREAD

**Issue by dragonstyle** [rstudio/rstudio#7364]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4
    OS Version      : MacOS Catalina
    R Version       : 4.0

### Steps to reproduce the problem
Switch to visual markdown mode. Insert X<smiley emoji>X.
Compare display on retina and non-retina displays. Note that Retina display includes very small emoji character and excess space to the right of the emoji character.

### Describe the problem in detail
Display of emojis characters in visual markdown mode on retina displays is broken. The emojis characters are rendered too small and with excess right padding. (See additional information in this Chromium Bug):

https://bugs.chromium.org/p/chromium/issues/detail?id=551420

We have worked around this bug in visual markdown mode by using CSS to increase the character size and apply a reduced right margin. If we ultimately take a version of Chromium that fixes this underlying issue, we need to remove the CSS changes in the commit that references this tracking issue.

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
### Commit to revert if Chromium fixes underlying issue
https://github.com/rstudio/rstudio/commit/fd350936c7c9426db3d3d5a751326d78f2f8f942

**Comment by dragonstyle** [comment]
Still not fixed as of Jan 2021, continue to track.
