### ISSUE TITLE
Creating a new project from inside an existing project can result in incomplete repo list in renv.lock file

### ISSUE THREAD

**Issue by cm421** [rstudio/rstudio#9947]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1106-5
    OS Version      : RHEL 8.4
    R Version       : 3.6.3

### Steps to reproduce the problem

This issue was brought to light in support ticket 66222, and seems related to work done for GH issue #7136. 

To create the issue:

See the steps listed in the post on Oct 01 at 10:51 of the support ticket. The issue comes to light in test 3.

### Describe the problem in detail

When creating a new project from a project that contains a renv lock file that does not have all the repos listed, the new project won't have all the repos listed either. Creating a new project and then calling `renv::init()` does include all the desired repos.

### Describe the behavior you expected

Creating a new project and ticking "use renv" should function the same as when making a new project and then manually calling `renv::init()`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This sounds like an issue that should be resolved in the most recent release of RStudio. See:

https://github.com/rstudio/rstudio/commit/d4eac9a41997739b693778f468c9dd2c211d4b62

From the commit, it appears the fix appeared in 1.4.1717.

**Comment by kevinushey** [comment]
And it's worth noting that `renv::snapshot()` just saves whatever repositories are currently active (as seen via `getOption("repos")`) into the lockfile, so whatever they see in the lockfile should be what they had active in the R session.

**Comment by mikebessuille** [comment]
@cm421 would you mind retesting this scenario per Kevin's comment above, and closing?

**Comment by cm421** [comment]
Apologies for this falling through the cracks. Testing on RStudio 2022.02.0+443.pro2 with `renv` 0.15.4 this still occurs.

### Part 1
Steps I took:

1. With only one repo listed in `getOption("repos")`, run `renv::init()` in a directory
2. Add a repo Tools->Global Options->Packages->Add Secondary Repo
3. `getOption("repos")` still only returns the one repo
    1. This is the root of the bug, but not necessarily the bug itself. Should it return the one repo listed in `renv.lock`, or the two repos from the options menu?
    2. `renv` for that given session seems to insulate from any changes made to the repolist

### Part 2
From here you can go two ways:

1. From that original directory and the same session from Part 1:
    1. Use the GUI to create a New R Project 
    2. Tick `use renv` 
    3. New project will initialize renv, but still only have one repo in `renv.lock` and `getOption("repos")`
        1. ie, in creating the new project we seem to have used the old `renv.lock` file (and its repos) of the directory we happened to be in
        2. Because the new project's `renv::init()` is called from a session that has an active `renv` with an olde repolist, the new project will also have the olde repolist when the session restarts/loads the new project. This is the actual bug.

OR:

4. From a new session and new directory:
    1. call `renv.init()`
    2. The 2 repos now show up in `renv.lock` and in getOption("repos")
        1. This is the expected behavior for both scenarios

**Comment by kevinushey** [comment]
Thanks; I think I misunderstood the issue as originally filed.

The underlying issue here is the disconnect between the repositories configured via the RStudio UI, and the repositories actually used in renv projects. The dialog tries to hint at that, with a warning message:

![image](https://user-images.githubusercontent.com/1976582/168699153-18be5c55-ed4e-4bab-ab7d-2171e7c5164a.png)

But "CRAN repositories modified outside package preferences" is not particularly clear.

For the `renv` case, we should say something explicit like:

> This project's repositories are managed by the renv package. These settings will not apply.

And (in the future? or for this release?) provide some actual UI for changing the repositories encoded in the renv lockfile.
